const asksData = {
	"0": {ask: "Can a dog love me?", like: false, anonymous: true },
	"1": {ask: "Can a dog love me?", like: true, anonymous: true },
	"2": {ask: "Can a dog love me?", like: false, anonymous: true },
	"3": {ask: "Can a dog love me?", like: false, anonymous: true },
	"4": {ask: "Can a dog love me?", like: true, anonymous: true },
	"5": {ask: "Can a dog love me?", like: false, anonymous: true },
	"6": {ask: "Can a dog love me?", like: true, anonymous: false },
	"7": {ask: "Can a dog love me?", like: false, anonymous: true },
	"8": {ask: "Can a dog love me?", like: false, anonymous: true },
	"9": {ask: "Can a dog love me?", like: false, anonymous: false },
	"10": { ask: "Can a dog love me?", like: false, anonymous: true },
	"11": { ask: "Can a dog love me?", like: false, anonymous: true },
	"12": { ask: "Can a dog love me?", like: false, anonymous: true },
	"13": { ask: "Can a dog love me?", like: false, anonymous: true },
	"14": { ask: "Can a dog love me?", like: false, anonymous: true },
	"15": { ask: "Can a dog love me?", like: false, anonymous: true },
	"16": { ask: "Can a dog love me?", like: false, anonymous: true },
	"17": { ask: "Can a dog love me?", like: false, anonymous: true },
	"18": { ask: "Can a dog love me?", like: false, anonymous: true },
	"19": { ask: "Can a dog love me?", like: false, anonymous: true },
	"20": { ask: "Can a dog love me?", like: false, anonymous: true },
	"21": { ask: "Can a dog love me?", like: false, anonymous: true },
	"22": { ask: "Can a dog love me?", like: false, anonymous: true },
	"23": { ask: "Can a dog love me?", like: false, anonymous: true },
	"24": { ask: "Can a dog love me?", like: false, anonymous: true },
	"25": { ask: "Can a dog love me?", like: false, anonymous: true },
};

export default asksData;